import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Philip Kaminski- web dev</h1>

        <p className={styles.description}>
          Website under construction. Meanwhile, check out{" "}
          <a href="https://github.com/AureaFlamma">my GitHub</a>
        </p>
      </main>
    </div>
  );
}
